### ISSUE TITLE
unglify and compress the js file

### ISSUE THREAD

**Issue by s890081tonyhsu** [NekowizTW/cardFinder#1]
Ref: http://www.zhangxinxu.com/wordpress/2013/01/uglifyjs-compress-js/

I've saw the file you upload, but maybe we didn't use some package to uglify and compress our js file before.

The following image is the test of what uglifyjs can minify the js file.

* app-min.js is doing only compress
* app.min.js is doing both uglify and compress

![image](https://cloud.githubusercontent.com/assets/3825000/20612226/8524af14-b2f2-11e6-9139-e954c42c177e.png)

Because our data is too big for a limited 3G and 4G users. So I don't want the source file eat too much bandwidth on that.

**Comment by FalseChord** [comment]
OK, will try to handle .js file, as well as .json file.

**Comment by FalseChord** [comment]
Use gulp-uglify to compress .js code.
Changes in commit d86e24c778bb407d7c0a0d7a0f663a80c41d7829.
