### ISSUE TITLE
特殊技能標籤重複

### ISSUE THREAD

**Issue by skkri** [NekowizTW/cardFinder#10]
特殊技能那邊有很多舊的標籤沒刪掉
導致如果搜尋舊的會什麼也搜不到
舉例來說
全體大魔術有
"大魔術/全體(給予全體傷害)"跟"大魔術(全體)"
如果搜尋前者就什麼也搜不到

**Comment by skkri** [comment]
再補充一下
心眼・絕跟心眼・破也搜不到
似乎是・有換過，但搜尋器還沒換的關係

**Comment by s890081tonyhsu** [comment]
特殊技能部份：
標籤「無」以下的技能是系統自動補全上去的，也就是說沒有在系統建設清單的狀況下他會自己補

心眼部份：
wiki上「心眼・破」中間點的utf8編碼是：\xe3\x83\xbb
本搜尋器「心眼‧破」中間點的utf8編碼是：\xe2\x80\xa7

若以上兩點以後wiki上會繼續使用該格式的話，我這邊會馬上補正。

**Comment by s890081tonyhsu** [comment]
@skkri 雖然已經解決了問題，不過有些技能類型末尾多了空白鍵，這部份可能麻煩你去在wiki勘查看看。

目前可以檢測到空白鍵的都是掛在「】」符號後面的，之後我有空會幫忙確認。

**Comment by william232918** [comment]
已確認過當前SS1與SS2共323+302項技能type的「】」後方皆沒有不可視的特殊符號或空格
心眼部分已於2018/02/17根據官方公告內的潛能名稱將「‧」全面替換成「・」
