### ISSUE TITLE
[feature] 潛能搜尋調整

### ISSUE THREAD

**Issue by alantea** [NekowizTW/cardFinder#11]
目前在潛能的搜尋中，若選擇 2 個以上的潛能，會將符合任一潛能的卡片篩選出來，造成卡片顯示過多
(簡單來說是採用 or 來篩選卡片)

希望改成符合所有選擇潛能的卡片才顯示，比較符合篩選的好處

**Comment by s890081tonyhsu** [comment]
程式碼區段在這，some是lodash中類似or的用法，所以轉換成and要研究一下。

https://github.com/NekowizTW/cardFinder/blob/master/src/scripts/Store/CardCollecStore.js#L133

**Comment by s890081tonyhsu** [comment]
程式原本的邏輯是用先用選定潛能去篩卡片上的潛能，假設選定三個潛能，那這張卡片的潛能清單(10+4)會被篩成0~3個潛能，之後再把0個的篩掉。

現在邏輯反過來，所以只要把被篩出3個潛能的留下即可。

（補充）不知道未來會不會強求潛能與L潛能分開計量，所以先看看玩家需求。
