### ISSUE TITLE
搜尋心眼會同時找到心眼跟心眼破

### ISSUE THREAD

**Issue by skkri** [NekowizTW/cardFinder#4]
在潛能/L發動能力搜尋心眼時
心眼‧破也會一起被搜尋到

**Comment by s890081tonyhsu** [comment]
所以預期是搜尋心眼時不能搜尋到心眼‧破是嗎?
因為搜尋手法的關係，這可能要研究一下

**Comment by skkri** [comment]
是得，因為心眼‧破也可以單獨搜尋
所以這兩個分開或許會比較好

**Comment by s890081tonyhsu** [comment]
改好了，目前先針對心眼這部分處理，不知道之後有沒有其他類似要做的._.
